# Validation

In [1]:
import pandas as pd

In [6]:
# Paths
PATH = '/home/tatiane/repositorios/brazil-health-data-project/data_pipeline'
xls_path = f"{PATH}/data/raw/ibge_codigos/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls"
parquet_path = f"{PATH}/data/processed/ibge_codigos/01_conversion/dtb_brasil_2024_municipios.parquet"

In [7]:
# Reading
df_xls = pd.read_excel(xls_path)
df_parquet = pd.read_parquet(parquet_path)

- Validation

In [11]:
comparacao = pd.concat([
    df_xls.dtypes.rename('tipo_xls'),
    df_parquet.dtypes.rename('tipo_parquet'),
    df_xls.isnull().sum().rename('nulos_xls'),
    df_parquet.isnull().sum().rename('nulos_parquet'),
    df_xls.nunique().rename('unicos_xls'),
    df_parquet.nunique().rename('unicos_parquet')
], axis=1)

comparacao['tipo_ok'] = comparacao['tipo_xls'] == comparacao['tipo_parquet']
comparacao['nulos_ok'] = comparacao['nulos_xls'] == comparacao['nulos_parquet']
comparacao['unicos_ok'] = comparacao['unicos_xls'] == comparacao['unicos_parquet']

In [12]:
comparacao.query("tipo_ok == False or nulos_ok == False or unicos_ok == False")

Empty DataFrame
Columns: [tipo_xls, tipo_parquet, nulos_xls, nulos_parquet, unicos_xls, unicos_parquet, tipo_ok, nulos_ok, unicos_ok]
Index: []

- Visão completa

In [8]:
resumo_xls = pd.DataFrame({
    'tipo': df_xls.dtypes,
    'nulos': df_xls.isnull().sum(),
    'perc_nulos': (df_xls.isnull().sum() / len(df_xls)) * 100,
    'unicos': df_xls.nunique()
})

resumo_xls

                                        tipo  nulos  perc_nulos  unicos
UF                                     int64      0     0.00000      27
Nome_UF                               object      0     0.00000      27
Região Geográfica Intermediária        int64      0     0.00000     133
Nome Região Geográfica Intermediária  object      0     0.00000     133
Região Geográfica Imediata             int64      0     0.00000     510
Nome Região Geográfica Imediata       object      0     0.00000     508
Município                              int64      0     0.00000    4308
Código Município Completo              int64      0     0.00000    5571
Nome_Município                        object      0     0.00000    5298
Unnamed: 9                            object   5570    99.98205       1

In [9]:
resumo_parquet = pd.DataFrame({
    'tipo': df_parquet.dtypes,
    'nulos': df_parquet.isnull().sum(),
    'perc_nulos': (df_parquet.isnull().sum() / len(df_parquet)) * 100,
    'unicos': df_parquet.nunique()
})

resumo_parquet

                                        tipo  nulos  perc_nulos  unicos
UF                                     int64      0     0.00000      27
Nome_UF                               object      0     0.00000      27
Região Geográfica Intermediária        int64      0     0.00000     133
Nome Região Geográfica Intermediária  object      0     0.00000     133
Região Geográfica Imediata             int64      0     0.00000     510
Nome Região Geográfica Imediata       object      0     0.00000     508
Município                              int64      0     0.00000    4308
Código Município Completo              int64      0     0.00000    5571
Nome_Município                        object      0     0.00000    5298
Unnamed: 9                            object   5570    99.98205       1