# Validation

In [5]:
import pandas as pd

In [8]:
# Paths
xls_path = "/home/tatiane/repositorios/brazil-health-data-project/data_pipeline/data/raw/ibge_codigos/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls"
parquet_path = "/home/tatiane/repositorios/brazil-health-data-project/data_pipeline/data/processed/ibge_codigos/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.parquet"

In [9]:
# Reading
df_xls = pd.read_excel(xls_path)
df_parquet = pd.read_parquet(parquet_path)

- Validation

In [11]:
print('Quantidade de registros do Dataset xls:', len(df_xls))
print('Quantidade de registros do Dataset parquet:', len(df_parquet))

Quantidade de registros do Dataset xls: 5571
Quantidade de registros do Dataset parquet: 5571

In [12]:
print('Colunas do Dataset xls:' , df_xls.columns.tolist())

Colunas do Dataset xls: ['UF', 'Nome_UF', 'Região Geográfica Intermediária', 'Nome Região Geográfica Intermediária', 'Região Geográfica Imediata', 'Nome Região Geográfica Imediata', 'Município', 'Código Município Completo', 'Nome_Município', 'Unnamed: 9']

In [13]:
print('Colunas do Dataset parquet:' , df_parquet.columns.tolist())

Colunas do Dataset parquet: ['UF', 'Nome_UF', 'Região Geográfica Intermediária', 'Nome Região Geográfica Intermediária', 'Região Geográfica Imediata', 'Nome Região Geográfica Imediata', 'Município', 'Código Município Completo', 'Nome_Município', 'Unnamed: 9']

In [14]:
df_xls.head(20)

,UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Unnamed: 9
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,NaN
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis,NaN
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso,NaN
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,346,1100346,Alvorada D'Oeste,NaN
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,23,1100023,Ariquemes,NaN
5,11,Rondônia,1101,Porto Velho,110002,Ariquemes,452,1100452,Buritis,NaN
6,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,31,1100031,Cabixi,NaN
7,11,Rondônia,1101,Porto Velho,110002,Ariquemes,601,1100601,Cacaulândia,NaN
8,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,49,1100049,Cacoal,NaN
9,11,Rondônia,1101,Porto Velho,110002,Ariquemes,700,1100700,Campo Novo de Rondônia,NaN
10,11,Rondônia,1101,Porto Velho,110001,Porto Velho,809,1100809,Candeias do Jamari,NaN
11,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,908,1100908,Castanheiras,NaN
12,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,56,1100056,Cerejeiras,NaN
13,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,924,1100924,Chupinguaia,NaN
14,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,64,1100064,Colorado do Oeste,NaN
15,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,72,1100072,Corumbiara,NaN
16,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,80,1100080,Costa Marques,NaN
17,11,Rondônia,1101,Porto Velho,110002,Ariquemes,940,1100940,Cujubim,NaN
18,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,98,1100098,Espigão D'Oeste,NaN
19,11,Rondônia,1101,Porto Velho,110003,Jaru,1005,1101005,Governador Jorge Teixeira,NaN

In [15]:
df_parquet.head(20)

,UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Unnamed: 9
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,None
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis,None
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso,None
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,346,1100346,Alvorada D'Oeste,None
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,23,1100023,Ariquemes,None
5,11,Rondônia,1101,Porto Velho,110002,Ariquemes,452,1100452,Buritis,None
6,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,31,1100031,Cabixi,None
7,11,Rondônia,1101,Porto Velho,110002,Ariquemes,601,1100601,Cacaulândia,None
8,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,49,1100049,Cacoal,None
9,11,Rondônia,1101,Porto Velho,110002,Ariquemes,700,1100700,Campo Novo de Rondônia,None
10,11,Rondônia,1101,Porto Velho,110001,Porto Velho,809,1100809,Candeias do Jamari,None
11,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,908,1100908,Castanheiras,None
12,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,56,1100056,Cerejeiras,None
13,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,924,1100924,Chupinguaia,None
14,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,64,1100064,Colorado do Oeste,None
15,11,Rondônia,1102,Ji-Paraná,110006,Vilhena,72,1100072,Corumbiara,None
16,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,80,1100080,Costa Marques,None
17,11,Rondônia,1101,Porto Velho,110002,Ariquemes,940,1100940,Cujubim,None
18,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,98,1100098,Espigão D'Oeste,None
19,11,Rondônia,1101,Porto Velho,110003,Jaru,1005,1101005,Governador Jorge Teixeira,None